function generate_components(app)

% Generate the following array of components
components = {
    @generate_roi_preview,...
    @generate_data_preview,...
    @generate_max_degree_structural_learning,...
    @generate_mean_degree_structural_learning,...
    @generate_median_degree_structural_learning,...
    @generate_rms_degree_structural_learning,...
    @generate_complexity_structural_learning,...
    @generate_parameter_space_structural_learning,...
    @generate_test_optimization_structural_learning,...
    @generate_training_optimization_structural_learning,...
    @generate_structural_learning_preview,...
    @generate_parameter_estimation_preview,...
    @generate_training_optimization_parameter_estimation,...
    @generate_testing_optimization_parameter_estimation,...
    @generate_edge_weight_parameter_estimation,...
    @generate_node_weight_parameter_estimation,...
    @generate_parameter_space_parameter_estimation,...
    @generate_model_decoding_evaluation,...
    @generate_model_evaluation,...
    @generate_model_relative_decoding,...
    @generate_node_performance_distribution,...
    @generate_ensemble_coordinates,...
    };

for func = 1:length(components)
    components{func}(app);
end

end
