function generate_components(app)

% Generate the following array of components
components = {
    @generate_roi_preview,...
    @generate_data_preview,...
    @generate_max_degree_structural_learning,...
    @generate_mean_degree_structural_learning,...
    @generate_median_degree_structural_learning,...
    @generate_rms_degree_structural_learning,...
    @generate_complexity_structural_learning,...
    };

for func = 1:length(components)
    components{func}(app);
end

end
